<?php
ob_start();
echo $form->render();
?>
<script>
	$(function(){
		$('form .element-group.submit').append('<input type="submit" value="Save & Create New" class="btn btn-primary" name="saveAndNew" />');
		$('#properties').live('keyup', justComma);

		$('input[name="name"]').live('keyup blur click', initCap);

		$('#extend').change(function(){
			if ($(this).val() == '') {
				$('#dbs').attr('checked', 'checked').parent().show();
			}
			else {
				$('#dbs').removeAttr('checked').parent().hide();
			}
		});
	});
</script>
<?php
$this->loadLayout('template', array(
	'heading' => $module . '\Models - New',
	'content' => ob_get_clean(),
	'class' => 'span8 offset2'
));