<?php
Table::init(array('class' => 'table table-striped'));
Table::setHeaders(array('Name', 'Model', 'Elements'));

foreach ($forms as $form => $modelArray) {
	list($model, $elementArray) = each($modelArray);
	Table::newRow();
	Table::addRowData($form);
	Table::addRowData($model);
	Table::addRowData(join(', ', $elementArray));
}

$this->loadLayout('template', array(
	'heading' => $module . '\Forms',
	'btns' => '<a href="' . $this->url('ds-util', 'forms', 'new', array('module' => $module)) . '" class="btn btn-success">New Form</a>',
	'content' => Table::render()
));