<?php
Table::init(array('class' => 'table table-striped'));
Table::setHeaders(array('Name', 'Model', 'Elements'));

$cnt = 1;
foreach ($fieldsets as $fieldset => $modelArray) {
	list($model, $elementArray) = each($modelArray);
	Table::newRow();
	Table::addRowData($fieldset);
	Table::addRowData($model);
	if (!empty($elementArray))
		Table::addRowData(join(', ', $elementArray));
	else
		Table::addRowData('');
	$cnt++;
}

$this->loadLayout('template', array(
	'heading' => $module . '\Fieldsets',
	'btns' => '<a href="' . $this->url('ds-util', 'fieldsets', 'new', array('module' => $module)) . '" class="btn btn-success">New Fieldset</a>',
	'content' => Table::render()
));