<?php
Table::init(array('class' => 'table table-striped'));
Table::setHeaders(array('Name', 'Model Class', 'Form'));

foreach ($services as $service => $array) {
	Table::newRow();
	Table::addRowData($service);
	Table::addRowData(!empty($array['modelClass']) ? $array['modelClass'] : 'default');
	Table::addRowData(!empty($array['form']) ? $array['form'] : 'default');
}

$this->loadLayout('template', array(
	'heading' => $module . '\Services',
	'btns' => '<a href="' . $this->url('ds-util', 'services', 'new', array('module' => $module)) . '" class="btn btn-success">New Service</a>',
	'content' => Table::render()
));
?>