<h1><small class="text-error">Welcome Admin</small></h1>
<hr />
<p>
	<span class="lead text-info">DScribe framework</span> offers you loads of opportunities and makes your software
	development process a helluva faster.
<p>
<p>
	This is the admin page and only logged in user may view it. <span class="lead text-info">DScribe framework</span> makes
	it easy working with users, controllers, models, services, forms and layouts (notice the links on the right?).
</p>
<p>
	Ensure you read the user guide and consult the documentations too.
</p>
