<h1><small class="text-error">Welcome</small></h1>
<hr />
<p>
	<span class="lead text-info">DScribe framework</span> offers you loads of opportunities and makes your software
	development process a helluva faster.
<p>
<p>
	Click on the admin link above to view the admin page. Note, you'll be required
	to login.
</p>
<p>
	Not to worry, it's just a demo. The username and password are
	<span class="text-info">"admin"</span> and <span class="text-info">"admin"</span>.
</p>