<?php ob_start(); ?>
<div class="span3">
	<ul class="nav nav-tabs nav-stacked">
		<li class="<?= ($this->controller() === 'models') ? 'active  disabled' : '' ?>"><a href="<?= $this->url('ds-util', 'models', 'index', array('module' => $module)) ?>">Models</a></li>
		<li class="<?= ($this->controller() === 'fieldsets') ? 'active  disabled' : '' ?>"><a href="<?= $this->url('ds-util', 'fieldsets', 'index', array('module' => $module)) ?>">Fieldsets</a></li>
		<li class="<?= ($this->controller() === 'forms') ? 'active  disabled' : '' ?>"><a href="<?= $this->url('ds-util', 'forms', 'index', array('module' => $module)) ?>">Forms</a></li>
		<li class="<?= ($this->controller() === 'controllers') ? 'active  disabled' : '' ?>"><a href="<?= $this->url('ds-util', 'controllers', 'index', array('module' => $module)) ?>">Controller</a></li>
		<li class="<?= ($this->controller() === 'services') ? 'active  disabled' : '' ?>"><a href="<?= $this->url('ds-util', 'services', 'index', array('module' => $module)) ?>">Services</a></li>
	</ul>
</div>
<div class="span9">
	<?= $content ?>
</div>
<?php
$this->loadLayout('main', array('content' => ob_get_clean()));